### ISSUE TITLE
Wasser immer gleich zeichnen

### ISSUE THREAD

**Issue by Alexx882** [Alexx882/SiegeAndDestroy3D#115]
Reproduce: 
Spieler B platziert ein Schiff vertikal. Spieler A zeigt das Board von Spieler B an (ohne dass schon Schüsse abgegeben werden). Das vertikale Schiff verursacht, dass die Ws für das Wasser gedreht angezeigt werden.
Bitte immer waagrecht anzeigen xD

**Comment by pareinwald** [comment]
Fixed
