### ISSUE TITLE
Login Logik Server

### ISSUE THREAD

**Issue by LauraKosir** [Alexx882/SiegeAndDestroy3D#9]
Checken der Namen für ein Spiel

**Comment by Alexx882** [comment]
Überprüfen des Namens eines Users und wenn der Name eindeutig (noch nicht genutzt ist) wird ein User Objekt erstellt und zurückgeschickt. Wenn der Name schon vorhanden ist, wird null zurückgeschickt.
Testen zb name="Laura" kregst User zrück, name="Laura" kregst Null zrück.
Id des User Objekts muss eindeutig sein (fortlaufend von 1)
